---
- name: Install and configure shared resources
  hosts: all
  become: true
  roles:
    - {role: common, tags: common}
    - {role: bash, tags: bash}
    - {role: neovim, tags: neovim}
    - {role: zsh, tags: zsh}

- name: Install and configure graphical resources
  hosts: graphical
  become: true
  roles:
    - {role: bspwm, tags: bspwm}
    - {role: mpd, tags: mpd}
    - {role: polybar, tags: polybar}
    - {role: rofi, tags: rofi}
    - {role: kitty, tags: kitty}

# vim: filetype=yaml.ansible
