---
standard_packages:
  - acpi
  - ansible
  - ansible-lint
  - autoconf
  - autogen
  - automake
  - base
  - bat
  - bind
  - calc
  - ctags
  - docker
  - docker-compose
  - dos2unix
  - fzf
  - gcc
  - gdb
  - git
  - git-lfs
  - gnu-netcat
  - gparted
  - btop
  - inetutils
  - jq
  - kitty
  - lshw
  - lsof
  - lvm2
  - make
  - man-db
  - mlocate
  - nmap
  - ntp
  - openssh
  - openvpn
  - pacman-contrib
  - patch
  - pkgconf
  - pwgen
  - ranger
  - ripgrep
  - samba
  - sshpass
  - stow
  - sudo
  - systemd-resolvconf
  - texinfo
  - traceroute
  - tree
  - units
  - valgrind
  - wget
  - whois
  - xdg-user-dirs
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  - zsh-theme-powerlevel10k

# Empty by default to allow the group_vars to define them
graphical_packages: []

# Empty by default to allow the group_vars to define them
headless_packages: []

theme: nord
user: "{{ lookup('env', 'USER') }}"
group: "{{ lookup('env', 'USER') }}"

# vim: filetype=yaml.ansible
