---
- name: Install bspwm and sxhkd
  ansible.builtin.package:
    name:
      - bspwm
      - sxhkd
    state: present
  tags:
    - packages

- name: Copy bspwm-session handler
  ansible.builtin.copy:
    src: bspwm-session
    dest: /usr/local/bin/bspwm-session
    owner: root
    group: root
    mode: 0755
  tags:
    - scripts

- name: Copy xsession desktop file
  ansible.builtin.copy:
    src: bspwm.desktop
    dest: /usr/share/xsessions/bspwm.desktop
    owner: root
    group: root
    mode: 0644
  tags:
    - scripts

- name: Create user configuration directories
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/{{ item }}/"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  with_items:
    - bspwm
    - sxhkd
  tags:
    - configuration

- name: Copy bspwm user files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.config/bspwm/{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  with_items:
    - autostart
    - bspwmrc
  tags:
    - configuration

- name: Copy sxhkd configuration
  ansible.builtin.copy:
    src: sxhkdrc
    dest: "{{ lookup('env', 'HOME') }}/.config/sxhkd/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  tags:
    - configuration
