#!/usr/bin/env bash

nitrogen --restore
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr

if ! pgrep picom; then
	picom --daemon --blur-background --no-vsync
fi

case $(hostnamectl --static) in
	ireland)
		polybar --reload ireland-primary &
		polybar --reload ireland-secondary &
		polybar --reload ireland-tertiary &
		pasystray &
		;;
	tir-na-nog)
		polybar --reload tir-na-nog-primary &
		polybar --reload tir-na-nog-secondary &
		polybar --reload tir-na-nog-tertiary &
		pasystray &
		;;
	wisp)
		setxkbmap -option ctrl:nocaps
		polybar --reload wisp &
		;;
	baile-mor)
		setxkbmap -option ctrl:nocaps
		polybar --reload baile-mor-primary &
		;;
	callisto)
		setxkbmap -option ctrl:nocaps
		autorandr --force --change &
		;;
esac
