---
- name: Install zsh and extensions
  ansible.builtin.package:
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-completions
      - zsh-history-substring-search
      - zsh-syntax-highlighting
      - zsh-theme-powerlevel10k
    state: present
  tags:
    - packages

- name: Copy .zshrc
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  tags:
    - configuration

- name: Create user configuration directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.zsh/"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  tags:
    - configuration

- name: Copy user files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.zsh/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  with_fileglob:
    - "*.zsh"
  tags:
    - configuration

# vim: filetype=yaml.ansible
