#!/usr/bin/env bash

export SXHKD_SHELL="/usr/bin/zsh"
export TERMINAL="kitty"
export EDITOR="nvim"
export VISUAL="nvim"
export SUDO_EDITOR="nvim"
export BROWSER="chromium"
export CALCULATOR="${TERMINAL} -e calc"
export FILE_BROWSER="thunar"
export IM_CLIENT="discord"
export IRC_CLIENT="hexchat"
export MAIL_CLIENT="${TERMINAL} -e mutt"
export MUSIC_PLAYER="${BROWSER} https://music.youtube.com/"
export VIRTUALIZATION="virt-manager"
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

export QUOTING_STYLE="literal"
export LC_ALL="en_US.UTF-8"

# Add custom scripts and utilities to PATH
export PATH="${PATH}:${HOME}/.local/bin:"

export FZF_DEFAULT_OPTS='
	--color fg:#D8DEE9,bg:#2E3440,hl:#A3BE8C,fg+:#D8DEE9,bg+:#434C5E,hl+:#A3BE8C
	--color pointer:#BF616A,info:#5E81AC,spinner:#5E81AC,header:#5E81AC,prompt:#81A1C1,marker:#EBCB8B'

export BAT_THEME="Nord"

# Avoid errors about the accessibility bus
export NO_AT_BRIDGE=1

# Fix Java GUI applications for tiling window managers
export _JAVA_AWT_WM_NONREPARENTING=1

# Source unversioned local customizations if they exist
if [ -f .profile.local ]; then
	source .profile.local
fi
