#!/usr/bin/env bash

export SXHKD_SHELL="/usr/bin/zsh"
export TERMINAL="kitty"
export EDITOR="nvim"
export VISUAL="nvim"
export SUDO_EDITOR="nvim"
export BROWSER="chromium"
export CALCULATOR="${TERMINAL} -e calc"
export FILE_BROWSER="thunar"
export IM_CLIENT="discord"
export IRC_CLIENT="hexchat"
export MAIL_CLIENT="${TERMINAL} -e mutt"
export MUSIC_PLAYER="${BROWSER} https://music.youtube.com/"
export VIRTUALIZATION="virt-manager"
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

export QUOTING_STYLE="literal"
export LC_ALL="en_US.UTF-8"

# Add custom scripts and utilities to PATH
export PATH="${PATH}:${HOME}/.local/bin:"

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
    --color=fg:#e5e9f0,hl:#81a1c1
    --color=fg+:#e5e9f0,hl+:#81a1c1
    --color=info:#eacb8a,prompt:#bf6069,pointer:#b48dac
    --color=marker:#a3be8b,spinner:#b48dac,header:#a3be8b'

export BAT_THEME="Nord"

# Avoid errors about the accessibility bus
export NO_AT_BRIDGE=1

# Fix Java GUI applications for tiling window managers
export _JAVA_AWT_WM_NONREPARENTING=1

# Source unversioned local customizations if they exist
if [ -f .profile.local ]; then
	source .profile.local
fi
