---
- name: Install rofi
  ansible.builtin.package:
    name:
      - rofi
    state: present
  tags:
    - packages

- name: Create user configuration directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/rofi/"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  tags:
    - configuration

- name: Copy configuration file
  ansible.builtin.template:
    src: config.rasi.j2
    dest: "{{ lookup('env', 'HOME') }}/.config/rofi/config.rasi"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  tags:
    - configuration

- name: Copy user files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.config/rofi/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  with_fileglob:
    - "*.rasi"
  tags:
    - configuration
