---
- name: Install rofi
  ansible.builtin.package:
    name:
      - rofi
    state: present
  tags:
    - packages

- name: Create user configuration directories
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  loop:
    - .config/rofi/
    - .local/share/rofi/themes/
  tags:
    - configuration

- name: Copy configuration file
  ansible.builtin.template:
    src: config.rasi.j2
    dest: "{{ lookup('env', 'HOME') }}/.config/rofi/config.rasi"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  tags:
    - configuration

- name: Copy theme files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/rofi/themes/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  with_fileglob:
    - "*.rasi"
  tags:
    - configuration

# vim: filetype=yaml.ansible
