---
- name: Start and enable user service
  ansible.builtin.systemd:
    name: mpd
    enabled: true
    scope: user
    state: started
  become: false

- name: Restart mpd
  ansible.builtin.systemd:
    name: mpd
    enabled: true
    scope: user
    state: restarted
  become: false

# vim: filetype=yaml.ansible
