---
- name: Install packages
  ansible.builtin.package:
    state: present
    name: "{{ lookup('community.general.flattened', standard_packages, graphical_packages, headless_packages) }}"
  tags:
    - packages

- name: Copy hidden user files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.{{ item | splitext | first }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0640
  loop:
    - profile
    - Xresources.{{ theme }}
    - dir_colors.{{ theme }}
    - LESS_TERMCAP
  tags:
    - configuration

- name: Create user bin directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0750
  tags:
    - scripts

- name: Install user scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  with_fileglob:
    - bin/*
  tags:
    - scripts

# vim: filetype=yaml.ansible
