---
- name: Install packages
  ansible.builtin.package:
    state: present
    name: "{{ lookup('community.general.flattened', standard_packages , graphical_packages, headless_packages) }}"
  tags:
    - packages

- name: Copy .profile
  ansible.builtin.copy:
    src: profile
    dest: "{{ lookup('env', 'HOME') }}/.profile"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  tags:
    - configuration

- name: Copy .Xresources
  ansible.builtin.copy:
    src: Xresources.{{ theme }}
    dest: "{{ lookup('env', 'HOME') }}/.Xresources"
    owner: "{{ user }}"
    group: "{{ group }}"
  when: "'graphical' in group_names"
  tags:
    - themes

- name: Copy .dir_colors
  ansible.builtin.copy:
    src: dir_colors.{{ theme }}
    dest: "{{ lookup('env', 'HOME') }}/.dir_colors"
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
    - themes

- name: Create user bin directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
    - scripts

- name: Install user scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  with_fileglob:
    - bin/*
  tags:
    - scripts
