---
- name: Install Vim
  ansible.builtin.package:
    name: vim
    state: latest
  when: "'headless' in group_names"
  tags:
    - packages

- name: Install GVim
  ansible.builtin.package:
    name: gvim
    state: latest
  when: "'graphical' in group_names"
  tags:
    - packages

- name: Create local runtime directories
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.vim/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775
  with_items:
    - after/ftplugin/
    - autoload/
    - plugged/
  tags:
    - configuration

- name: Install Vim package manager
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ lookup('env', 'HOME') }}/.vim/autoload/plug.vim"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0664
  tags:
    - configuration
    - plugins

- name: Copy runtime files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.vim/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0664
  with_items:
    - vimrc
    - after
  tags:
    - configuration
